# Generated by Django 5.2.4 on 2025-08-01 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0002_account_balance_statementitem_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statementitem',
            old_name='text',
            new_name='comments',
        ),
    ]
